ejemplo/ColegioA/Apps/home/urls.py
"""from xml.etree.ElementInclude import include"""
"""from turtle import home"""

from django.contrib import admin
from django.urls import path,include
from Apps.home import views
from .views import HomeView,ListadoView
app_name='home'


urlpatterns = [
    path('',HomeView.as_view(), name='homeapp'),
    path('listado/',ListadoView.as_view(), name='listadoapp')
]

ejemplo/ColegioA/ColegioA/urls.py
<<<<<<< HEAD
"""from xml.etree.ElementInclude import include"""
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('Apps.home.urls','home'))
=======
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
>>>>>>> 2d18fdc7fa471218cd26f7a84e5f16eb102b3189
]

ejemplo/ColegioA/Apps/home/models.py
from django.db import models

# Create your models here.

ejemplo/ColegioA/Apps/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomeView(TemplateView):
    template_name='home.html'

class ListadoView(TemplateView):
    template_name='listado.html'

ejemplo/ColegioA/Apps/home/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Home</h1>
    <a href={% url 'home:listadoapp' %} title="Mi enlace" class="nav-link">listado</a>
</body>
</html>

ejemplo/ColegioA/Apps/home/templates/listado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listado</title>
</head>
<h1>Los listados se muestran de la siguiente manera:</h1>
<h2>-------------------------------------------------</h2>
<body>
    <a href={% url 'home:homeapp' %} title="Mi enlace" class="nav-link">home</a>
    
</body>
</html>